name: ci

on: 
  push: 
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x.x
      - name: Log versions
        run: |
          deno --version
      # Lint
      - name: Format TS
        run: deno fmt --check    
      # Tests
      - name: Test TS
        run: deno test ./test.ts
    
